### ISSUE TITLE
添加到chrome扩展程序时报错：缺少清单

### ISSUE THREAD

**Issue by NewSword-zh** [kedpter/vip-player-plugin#1]
老哥 是不是我添加方法有问题 我之间把这个文件解压拖到chrome里 是不是中间缺了一步 我看你这里面是js 是不是要用油猴之类工具

**Comment by kedpter** [comment]
不用油猴之类的工具。能翻墙的话，可以去谷歌商店下载一下，我发布出去了https://chrome.google.com/webstore/detail/hkjmkgflkdnkdbhgomjghknpfhinkonn/publish-accepted?authuser=1&hl=zh-CN

**Comment by NewSword-zh** [comment]
明白 谢谢老哥




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kedpter"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 下午5:04
收件人:&nbsp;"kedpter/vip-player-plugin"<vip-player-plugin@noreply.github.com&gt;;
抄送:&nbsp;"青雀"<2687815997@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kedpter/vip-player-plugin] 添加到chrome扩展程序时报错：缺少清单 (#1)





 
不用油猴之类的工具。能翻墙的话，可以去谷歌商店下载一下，我发布出去了https://chrome.google.com/webstore/detail/hkjmkgflkdnkdbhgomjghknpfhinkonn/publish-accepted?authuser=1&amp;hl=zh-CN
